language: python

matrix:
  fast_finish: true
  include:
    - python: pypy
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: 3.5
    - python: 3.4

cache: pip

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install coverage
  - pip install pycodestyle pyflakes

script:
  # Static analysis
  - pyflakes .
  - pycodestyle --statistics --count .

  # Unit tests
  - coverage run --source tinytext setup.py test

  # Test install works
  - python setup.py install

after_success:
    # Report coverage and send to Codecov
  - coverage report
  - pip install codecov && codecov
