dist: xenial
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=lint
    - python: 3.7
      env: DEPLOYER=true
    - python: 3.6
    - python: 3.8-dev

install:
  - pip install -U pip
  - pip install -U tox-travis

script:
  - tox

after_success:
  - |
    if [ "$TOXENV" != "lint" ]; then
      pip install codecov && codecov
    fi

deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    on:
      tags: false
      repo: hugovk/tinytext
      branch: master
      condition: $DEPLOYER = true
    user: hugovk
    password:
      secure: "SOEzeD1SylX6UqPXAfY3gAwvM46s1gUv+YwpRb7qkT4ugO0uWw1D5DaYHve8/GxHTpjIZF+YVG0JE9Rpd57wYbfiqULBLrFugOlE17DikeP1ic2ZUh0UP0RGilAAaJuJv9bsda5dbbri4DHWmequQ0iF5r7TtdkHCpdq4SCHQefbczn7457eX8/3Vl+McmZAg6ghNF1zjsFl2r1uBuBJGfLhNs5g5szwh3c2oAogMeHFgqClQO2nuMhNmZrTk75ON2Toz+Jo9IASgg7AI3+Ump/VrZXqfmp3KFcngBJ8DUgGtWx2luqfSB5Dy8KcZmmeToJpsABoHJk1B397pNKKAFLrNfjixGgXEKoTL9Qcx59dY5vFiLn64u09bXFQIy6jhmDpCnwEbgTOUqTuwpv6BDiiSTZFC5sjf+eV/jNj11X53NZEPxqsYDZY0rTK6/lxflYD5VsjjhOVYNlWsOaV2CjMglAahv/79Jd2BUB7CQDSMJmDF2LWBgQXVA6iGkLbU09xEHo4AVsh753ox80wDYTqT+jgc+Vem6t7LK9MI6vErn4KQp1MzIl4k4+XGN82J8j4SoenQ7dDASInEJxvRUl7QJ50OFttA4wIGQjaSBDJv87pGaedKkhivqIZTd8QyrM2J99Vi45BCcB9cFb/0FTBOwVjqdTHTxY7dk0San8="
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
  - provider: pypi
    on:
      tags: true
      repo: hugovk/tinytext
      branch: master
      condition: $DEPLOYER = true
    user: hugovk
    password:
      secure: "SOEzeD1SylX6UqPXAfY3gAwvM46s1gUv+YwpRb7qkT4ugO0uWw1D5DaYHve8/GxHTpjIZF+YVG0JE9Rpd57wYbfiqULBLrFugOlE17DikeP1ic2ZUh0UP0RGilAAaJuJv9bsda5dbbri4DHWmequQ0iF5r7TtdkHCpdq4SCHQefbczn7457eX8/3Vl+McmZAg6ghNF1zjsFl2r1uBuBJGfLhNs5g5szwh3c2oAogMeHFgqClQO2nuMhNmZrTk75ON2Toz+Jo9IASgg7AI3+Ump/VrZXqfmp3KFcngBJ8DUgGtWx2luqfSB5Dy8KcZmmeToJpsABoHJk1B397pNKKAFLrNfjixGgXEKoTL9Qcx59dY5vFiLn64u09bXFQIy6jhmDpCnwEbgTOUqTuwpv6BDiiSTZFC5sjf+eV/jNj11X53NZEPxqsYDZY0rTK6/lxflYD5VsjjhOVYNlWsOaV2CjMglAahv/79Jd2BUB7CQDSMJmDF2LWBgQXVA6iGkLbU09xEHo4AVsh753ox80wDYTqT+jgc+Vem6t7LK9MI6vErn4KQp1MzIl4k4+XGN82J8j4SoenQ7dDASInEJxvRUl7QJ50OFttA4wIGQjaSBDJv87pGaedKkhivqIZTd8QyrM2J99Vi45BCcB9cFb/0FTBOwVjqdTHTxY7dk0San8="
    distributions: sdist --format=gztar bdist_wheel
    skip_existing: true
