language: python

python:
  - pypy3
  - 3.7-dev
  - 3.6
  - 3.5
  - 3.4

sudo: false

cache: pip

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install coverage
  - pip install pycodestyle pyflakes

script:
  # Static analysis
  - pyflakes .
  - pycodestyle --statistics --count .

  # Unit tests
  - coverage run --source tinytext setup.py test

  # Test install works
  - python setup.py install

after_success:
    # Report coverage and send to Codecov
  - coverage report
  - pip install codecov && codecov

matrix:
  fast_finish: true
