dist: xenial
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
    - python: 3.6
    - python: 3.8-dev

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -e ".[dev]"

script:
  # Static analysis
  - pre-commit run --all-files

  # Unit tests
  - pytest --cov tinytext

after_success:
    # Report coverage and send to Codecov
  - coverage report
  - pip install -U codecov && codecov
