[tool.black]
target_version = ["py37"]

[tool.flake8]
max_line_length = "88"

[tool.isort]
profile = "black"

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "-W error::DeprecationWarning"
