[tool.black]
target_version = ["py37"]

[tool.isort]
profile = "black"

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "-W error::DeprecationWarning"

[tool.setuptools_scm]
local_scheme = "no-local-version"
