name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow

      - name: pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: lint-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            lint-pip-

      - name: pre-commit cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: lint-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            lint-pre-commit-

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools setuptools_scm tox

      - name: Lint
        run: tox -e lint

      - name: Check version
        run: |
          python setup.py --version
          [ `python setup.py --version` != "0.0.0" ]
