name: Pre-commit update

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit

      - name: Check for updates
        run: |
          pre-commit autoupdate
          git status --porcelain
          test $(git status --porcelain| wc -l) = 0
