name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-latest]
        include:
          # Include new variables for Codecov
          - { codecov-flag: GHA_Ubuntu2004, os: ubuntu-20.04 }
          - { codecov-flag: GHA_Ubuntu1804, os: ubuntu-18.04 }
          - { codecov-flag: GHA_Ubuntu1604, os: ubuntu-16.04 }
          - { codecov-flag: GHA_macOS, os: macos-latest }
          # Dev versions
          - { python-version: 3.9-dev, os: ubuntu-20.04 }
          - { python-version: 3.10-dev, os: ubuntu-20.04 }

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} (deadsnakes)
        uses: deadsnakes/action@v1.0.0
        if: endsWith(matrix.python-version, '-dev')
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python ${{ matrix.python-version }}
        if: "!endsWith(matrix.python-version, '-dev')"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key:
            ${{ matrix.os }}-${{ matrix.python-version }}-v2-${{
            hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python-version }}-v2-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
          python -m pip install -U tox

      - name: Tox tests
        shell: bash
        run: |
          tox -e py

      - name: Upload coverage
        if: success()
        run: |
          curl --retry 8 -s https://codecov.io/bash -o codecov.sh
          bash codecov.sh -F ${{ matrix.codecov-flag }}
        env:
          CODECOV_NAME: ${{ matrix.os }} Python ${{ matrix.python-version }}
